version: "3.7"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    hostname: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - /media/nguyenphucthinh/DATA/db/mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: db
      PMA_USER: "root"
      PMA_PASSWORD: "root"
