version: '3.7'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 3000:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
  db:
    image: mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    hostname: kidp2h_localhost
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 5000:5000
    volumes:
      - ./src/server/socket/:/app
