version: '3.7'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      php_network:
        ipv4_address: 172.26.22.100
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 3000:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: ${HOST_MYSQL}
      PMA_USER: ${USERNAME_MYSQL}
      PMA_PASSWORD: ${PASSWORD_MYSQL}
    networks:
      php_network:
        ipv4_address: 172.26.22.101
  db:
    image: mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    hostname: kidp2h_localhost
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      php_network:
        ipv4_address: 172.26.22.102
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 5000:5000
    volumes:
      - ./src/server/socket/:/app
    networks:
      php_network:
        ipv4_address: 172.26.22.103
networks:
  php_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.22.0/24
