version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./cert.crt:/etc/ssl/certs/cert.crt
      - ./cert.key:/etc/ssl/private/cert.key
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 3000:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
  db:
    image: mysql
    hostname: kidp2h
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 5000:5000
    volumes:
      - ./src/server/socket/:/app
