version: '3.7'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      php_network:
        ipv4_address: 172.26.22.100
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      php_network:
        ipv4_address: 172.26.22.122
  db:
    image: mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    hostname: kidp2h_localhost
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      php_network:
        ipv4_address: 172.26.22.102
networks:
  php_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.22.0/24
